
# 📊 Retail Sales Data Analytics Project

This project focuses on the End-to-End Data Engineering and Exploratory Data Analysis (EDA) of a retail dataset containing 7,500 transaction records across major cities in Tamil Nadu, India. The notebook covers data ingestion, automated profiling, feature engineering, metric measurement, and advanced interactive visualizations.

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
from google.colab import files

upload=files.upload()

Saving retail_sales_dataset_7500 (1).csv to retail_sales_dataset_7500 (1).csv

In [ ]:
df=pd.read_csv('retail_sales_dataset_7500 (1).csv')


# Step 2: Automated Exploratory Data Analysis (EDA)

Instead of manual string-by-string checks, the notebook installs and leverages advanced profiling tools to generate a standalone HTML diagnostic report of the dataset schema, data distributions, and missing values.

In [ ]:
!pip install fg-data-profiling numpy pandas --quiet

from data_profiling import ProfileReport

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 400.5/400.5 kB 7.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 296.7/296.7 kB 18.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 34.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 682.5/682.5 kB 18.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 106.3/106.3 kB 5.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.0/72.0 kB 2.6 MB/s eta 0:00:00

In [ ]:
profile=ProfileReport(df,title='Retail sales data',explorative=True)

profile.to_file('Retail sales data.html')

files.download('Retail sales data.html')

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/12 [00:00<?, ?it/s]
 17%|█▋        | 2/12 [00:00<00:01,  6.36it/s]
 58%|█████▊    | 7/12 [00:00<00:00, 18.01it/s]
100%|██████████| 12/12 [00:00<00:00, 17.40it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [ ]:
df.head()

,order_id,customer_name,city,region,category,product,sales,discount_percent,profit,quantity,payment_mode,order_date
0,1,George Harris,Trichy,East,Sports,Cricket Bat,42204.19,23.70,7579.02,8,UPI,2024-10-16
1,2,Christopher Shannon,Chennai,East,Groceries,Oil,36664.41,10.21,6428.30,2,Card,2024-09-05
2,3,Amanda Baker,Madurai,South,Furniture,Sofa,43582.84,26.96,6726.70,3,Net Banking,2024-04-14
3,4,Shannon Baker,Madurai,West,Electronics,Laptop,21081.72,14.60,1172.83,6,Net Banking,2025-09-06
4,5,Beverly Williams,Madurai,West,Electronics,Laptop,7115.72,26.85,885.38,9,UPI,2024-11-19

In [ ]:
df.columns

Index(['order_id', 'customer_name', 'city', 'region', 'category', 'product',
       'sales', 'discount_percent', 'profit', 'quantity', 'payment_mode',
       'order_date'],
      dtype='object')


# Step 3: Schema Identification

A structured structural review evaluates the layout of the dataset. The data consists of 12 base columns combining categorical operational dimensions and numerical metric spaces:

In [ ]:
df.dtypes

order_id              int64
customer_name        object
city                 object
region               object
category             object
product              object
sales               float64
discount_percent    float64
profit              float64
quantity              int64
payment_mode         object
order_date           object
dtype: object


# Step 4: Temporal Feature Engineering

The baseline order_date column is parsed from a generic text object string type into a structural datetime64[ns] system type. This transformation unlocks exact time-series feature decomposition:

# Month dataset clean

In [ ]:
# order_date change to datetime
df['order_date'] = pd.to_datetime(df['order_date'])

In [ ]:
df.dtypes

order_id                     int64
customer_name               object
city                        object
region                      object
category                    object
product                     object
sales                      float64
discount_percent           float64
profit                     float64
quantity                     int64
payment_mode                object
order_date          datetime64[ns]
dtype: object

In [ ]:
df['month_name']=df['order_date'].dt.month_name()

df['month_num']=df['order_date'].dt.month

df['quarter']=df['order_date'].dt.quarter

df['year']=df['order_date'].dt.year

In [ ]:
df

,order_id,customer_name,city,region,category,product,sales,discount_percent,profit,quantity,payment_mode,order_date,month_name,month_num,quarter,year
0,1,George Harris,Trichy,East,Sports,Cricket Bat,42204.19,23.70,7579.02,8,UPI,2024-10-16,October,10,4,2024
1,2,Christopher Shannon,Chennai,East,Groceries,Oil,36664.41,10.21,6428.30,2,Card,2024-09-05,September,9,3,2024
2,3,Amanda Baker,Madurai,South,Furniture,Sofa,43582.84,26.96,6726.70,3,Net Banking,2024-04-14,April,4,2,2024
3,4,Shannon Baker,Madurai,West,Electronics,Laptop,21081.72,14.60,1172.83,6,Net Banking,2025-09-06,September,9,3,2025
4,5,Beverly Williams,Madurai,West,Electronics,Laptop,7115.72,26.85,885.38,9,UPI,2024-11-19,November,11,4,2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7495,7496,Paul Lutz,Chennai,West,Sports,Football,31109.25,5.65,1868.70,2,Cash,2024-07-23,July,7,3,2024
7496,7497,Kristen Nichols,Chennai,North,Groceries,Milk,36463.95,12.81,6778.32,1,Cash,2025-01-22,January,1,1,2025
7497,7498,Brandon Adkins,Tirunelveli,North,Furniture,Chair,42692.31,10.00,4727.10,6,UPI,2024-09-27,September,9,3,2024
7498,7499,Karen Davidson,Madurai,South,Furniture,Chair,29658.17,21.13,5632.31,6,Card,2025-01-18,January,1,1,2025
7499,7500,Veronica Howell,Madurai,South,Electronics,Laptop,2912.79,1.75,357.65,2,Net Banking,2025-12-29,December,12,4,2025

# measure data

In [ ]:
df.columns

Index(['order_id', 'customer_name', 'city', 'region', 'category', 'product',
       'sales', 'discount_percent', 'profit', 'quantity', 'payment_mode',
       'order_date', 'month_name', 'month_num', 'quarter', 'year'],
      dtype='object')

## 1. Total Unique Customers
Calculate the total number of **unique customers** in the retail dataset.

In [ ]:
# Total customer

total_customer =df['customer_name'].nunique()

print("Total Customer : ",total_customer)

Total Customer :  7128

In [ ]:
print("="*50)
print("           RETAIL DATASET SUMMARY")
print("="*50)

print(f"Total Orders           : {df['order_id'].nunique()}")
print(f"Total Unique Customers : {df['customer_name'].nunique()}")
print(f"Total Categories       : {df['category'].nunique()}")
print(f"Total Products         : {df['product'].nunique()}")
print(f"Total Cities           : {df['city'].nunique()}")
print(f"Total Regions          : {df['region'].nunique()}")
print(f"Total Sales            : ₹{df['sales'].sum():,.2f}")
print(f"Total Profit           : ₹{df['profit'].sum():,.2f}")
print(f"Avg Discount %         : {df['discount_percent'].mean():.2f}%")
print(f"Date Range             : {df['order_date'].min()} to {df['order_date'].max()}")
print("="*50)

==================================================
           RETAIL DATASET SUMMARY
==================================================
Total Orders           : 7500
Total Unique Customers : 7128
Total Categories       : 5
Total Products         : 20
Total Cities           : 6
Total Regions          : 4
Total Sales            : ₹188,546,725.57
Total Profit           : ₹28,384,774.78
Avg Discount %         : 14.96%
Date Range             : 2024-01-01 00:00:00 to 2025-12-31 00:00:00
==================================================

In [ ]:
# Total sales

total_sales=round(df['sales'].sum(),2)

print("Total sales : ",total_sales)

Total sales :  188546725.57

In [ ]:
# Average Profit

avg_profit = round(df['profit'].mean(),2)

print('averge profit : ', avg_profit)

averge profit :  3784.64

## Region-wise Sales Analysis

Calculate the **total sales generated in each region** to identify top-performing and underperforming regions.

In [ ]:
region_wise_sales=df.groupby('region')['sales'].sum()

print('Region wise sales: ', region_wise_sales)

Region wise sales:  region
East     47065554.03
North    48449603.86
South    47698472.27
West     45333095.41
Name: sales, dtype: float64

## Top 5 Products by Sales

Identify the **top 5 best-selling products** by total revenue to understand which products drive the most sales.

In [ ]:
# Top 5 Product

df['product'].unique()

print('Top 5 product')


top_5_product=df.groupby('product')['sales'].sum().nlargest(5)

# top_5_product=(df.groupby('product')['sales'].sum().sort_values(ascending=False).head(5))

# top_5_product=(df.groupby(['category','product'])['sales'].sum().sort_values(ascending=False).head(5))

print('Top 5 product : ',top_5_product)

Top 5 product
Top 5 product :  product
Cricket Bat    10627356.95
Cupboard       10176026.11
Table          10118540.19
Mobile          9779948.59
Jeans           9738303.64
Name: sales, dtype: float64

## City-wise Sales Analysis

Calculate the **total sales for each city** and rank them to identify the top-performing and weakest cities.

In [ ]:
# city wise sales

city_by_sales = df.groupby('city')['sales'].sum().sort_values(ascending=False)

print('city by sales : ',city_by_sales)

city by sales :  city
Chennai        32239086.17
Madurai        31840609.98
Salem          31582831.27
Trichy         31143733.44
Coimbatore     31080424.69
Tirunelveli    30660040.02
Name: sales, dtype: float64

## High & Low Sales Months Analysis

Identify the **top 5 highest-performing months** and **bottom 5 lowest-performing months** by total sales to understand seasonality and plan inventory/marketing accordingly.

In [ ]:

# Top 5 high sales months
high_sales_month = (
    df.groupby('month_name')['sales'].sum().sort_values(ascending=False).head(5)
)
print('\n High Sales Months:\n ', high_sales_month)

# Top 5 low sales months
low_sales_month = (
    df.groupby('month_name')['sales'].sum().sort_values(ascending=True).head(5)
)
print('\n Low Sales Months: \n', low_sales_month)

 High Sales Months:
  month_name
July         17594195.43
August       16350247.20
January      16258986.02
September    16230404.28
November     16078242.30
Name: sales, dtype: float64

 Low Sales Months:
 month_name
May         14736524.03
February    14766210.95
June        14781566.94
April       14823078.83
March       15235777.61
Name: sales, dtype: float64

## Product-wise Summary (Multi-Metric Analysis)
Build a **consolidated product-level summary** that shows units sold, total sales, total profit, and number of unique orders for each product — then rank products by units sold.

In [ ]:
product_summary = (
    df.groupby('product').agg(
                             unit_sold=('quantity', 'sum'),
                             total_sales=('sales', 'sum'),
                             total_profit=('profit', 'sum'),
                             orders=('order_id', 'nunique')
      )
      .sort_values('unit_sold', ascending=False)
)

print("Product-wise Summary (Top 10):")
print(product_summary.head(10))

Product-wise Summary (Top 10):
             unit_sold  total_sales  total_profit  orders
product
Cricket Bat       2316  10627356.95    1589647.58     415
Mobile            2276   9779948.59    1439152.07     400
Table             2158  10118540.19    1487141.54     407
Rice              2153   9503077.06    1411291.98     386
Kurti             2143   9573507.35    1408899.41     387
Sofa              2130   9250282.61    1388473.00     377
Laptop            2104   9115600.37    1417496.38     375
Cupboard          2078  10176026.11    1549087.10     385
Jeans             2054   9738303.64    1480822.28     386
T-Shirt           2049   9635255.31    1446653.73     389

# How many orders used each payment mode.

**Business Insight**

Shows which payment mode is most popular by order count.

UPI leading → digital-first customer base.

In [ ]:
payment_count = (
    df.groupby('payment_mode', as_index=False)['order_id']
      .count()
      .rename(columns={'order_id': 'orders'})
      .sort_values('orders', ascending=False)
)
print(payment_count)

  payment_mode  orders
3          UPI    1920
1         Cash    1884
0         Card    1852
2  Net Banking    1844

# Data visualization

**Installing Plotly**

Install **Plotly**, an interactive plotting library, to create dynamic charts (hover tooltips, zoom, pan) for the retail sales analysis.

### Command
pip install plotly

In [ ]:
pip install plotly

Requirement already satisfied: plotly in /usr/local/lib/python3.13/dist-packages (5.24.1)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.13/dist-packages (from plotly) (9.1.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from plotly) (26.3)

In [ ]:
import plotly.express as px

In [ ]:
df

,order_id,customer_name,city,region,category,product,sales,discount_percent,profit,quantity,payment_mode,order_date,month_name,month_num,quarter,year
0,1,George Harris,Trichy,East,Sports,Cricket Bat,42204.19,23.70,7579.02,8,UPI,2024-10-16,October,10,4,2024
1,2,Christopher Shannon,Chennai,East,Groceries,Oil,36664.41,10.21,6428.30,2,Card,2024-09-05,September,9,3,2024
2,3,Amanda Baker,Madurai,South,Furniture,Sofa,43582.84,26.96,6726.70,3,Net Banking,2024-04-14,April,4,2,2024
3,4,Shannon Baker,Madurai,West,Electronics,Laptop,21081.72,14.60,1172.83,6,Net Banking,2025-09-06,September,9,3,2025
4,5,Beverly Williams,Madurai,West,Electronics,Laptop,7115.72,26.85,885.38,9,UPI,2024-11-19,November,11,4,2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7495,7496,Paul Lutz,Chennai,West,Sports,Football,31109.25,5.65,1868.70,2,Cash,2024-07-23,July,7,3,2024
7496,7497,Kristen Nichols,Chennai,North,Groceries,Milk,36463.95,12.81,6778.32,1,Cash,2025-01-22,January,1,1,2025
7497,7498,Brandon Adkins,Tirunelveli,North,Furniture,Chair,42692.31,10.00,4727.10,6,UPI,2024-09-27,September,9,3,2024
7498,7499,Karen Davidson,Madurai,South,Furniture,Chair,29658.17,21.13,5632.31,6,Card,2025-01-18,January,1,1,2025
7499,7500,Veronica Howell,Madurai,South,Electronics,Laptop,2912.79,1.75,357.65,2,Net Banking,2025-12-29,December,12,4,2025

# Month wise Sales

In [ ]:

sales_month = (
    df.groupby(['month_num', 'month_name'], as_index=False)['sales']
      .sum()
      .sort_values('month_num')
)

fig = px.line(
              sales_month,
              x='month_name',
              y='sales',
              title='Monthly Sales',
              labels={'month_name': 'Month', 'sales': 'Total Sales'},
              color_discrete_sequence=['#5d9854']
)
fig.show()

# Top 5 Products by Quantity

Identify and visualize the **top 5 products** based on **total units sold**, using an interactive Plotly bar chart.

In [ ]:
import plotly.express as px

top5 = (
    df.groupby('product', as_index=False)['quantity']
      .sum()
      .sort_values('quantity', ascending=False)
      .head(5)
)

fig = px.bar(
    top5,
    y='product',
    x='quantity',
    title='Top 5 Products by Quantity',
    orientation='h',
    labels={
        'product': 'Product Name',
        'quantity': 'Total Quantity'
    },
    color_discrete_sequence=['blue']
)

fig.update_layout(
    plot_bgcolor='lightgray',
    paper_bgcolor='white'

)

fig.show()

# Sales by Category
Visualize the **share of total sales contributed by each product category** using an interactive Plotly pie chart.

In [ ]:
# Sales by Category

fig=px.pie(df,values='sales',names='category',title='sales by category')

fig.show()

# How many orders used each payment mode.

In [ ]:
import plotly.express as px

# Basic count
payment_count = (
    df.groupby('payment_mode', as_index=False)['order_id']
      .count()
      .rename(columns={'order_id': 'orders'})
      .sort_values('orders', ascending=False)
)
print(payment_count)

# Pie chart
fig = px.pie(
    payment_count,
    values='orders',
    names='payment_mode',
    title='Orders by Payment Mode'
)
fig.show()

  payment_mode  orders
3          UPI    1920
1         Cash    1884
0         Card    1852
2  Net Banking    1844

In [ ]:
df.columns

Index(['order_id', 'customer_name', 'city', 'region', 'category', 'product',
       'sales', 'discount_percent', 'profit', 'quantity', 'payment_mode',
       'order_date', 'month_name', 'month_num', 'quarter', 'year'],
      dtype='object')

# As discount changes, what happens to profit?

In [ ]:
fig = px.scatter(
    df,
    x='discount_percent',
    y='profit',
    size='sales',              # bubble size = sales
    color='category',
    title='Profit vs Discount (Bubble = Sales)',
    opacity=0.5,
    hover_data=['product', 'quantity'],
    size_max=40
)
fig.show()

## Sales Distribution Analysis

Understand the **distribution of individual order values** — are orders mostly small, medium, or large? Is the data skewed? Are there unusual patterns?

Feature	        Observation

Shape	  =       Nearly flat / roughly uniform from ₹0 to ₹50K

Y-axis	 =      Counts ~130–180 per bin (very consistent)

X-axis	 =      Sales from ₹0 to ₹50K

Peak     =      Around ₹43K–44K (~175 orders)

Lowest bins	=   Around ₹17K (~132 orders)

Overall pattern = No peak, no long tail → uniform distribution

In [ ]:
# Sales distribution
fig = px.histogram(
    df,
    x='sales',
    title='Sales Distribution',
    nbins=50
)
fig.show()

## Outlier Analysis — Sales by Category


Identify unusual sales values (outliers) within each product category using a box plot.

In [ ]:
# Outlier analysis

fig=px.box(df,x='category',y='sales',title='Outlier analysis')

fig.show()

## Sales Hierarchy Treemap (Category → Product)


Visualize how total sales are distributed across a **two-level hierarchy**: Category (parent) → Product (child), using nested rectangles.

In [ ]:
fig=px.treemap(df,path=['category','product'],values='sales',title='sales hierarchy')

fig.show()

Adds latitude and longitude to each row based on the city — enabling geographic visualization (maps, scatter maps, etc.).

In [ ]:
city_coordinates = {
    'Chennai': (13.0827, 80.2707),
    'Madurai': (9.9252, 78.1198),
    'Salem': (11.6643, 78.1460),
    'Trichy': (10.7905, 78.7047),
    'Coimbatore': (11.0168, 76.9558),
    'Tirunelveli': (8.7139, 77.7567)
}

df['latitude'] = df['city'].map(lambda x: city_coordinates[x][0])
df['longitude'] = df['city'].map(lambda x: city_coordinates[x][1])

In [ ]:
df.head(3)

,order_id,customer_name,city,region,category,product,sales,discount_percent,profit,quantity,payment_mode,order_date,month_name,month_num,quarter,year
0,1,George Harris,Trichy,East,Sports,Cricket Bat,42204.19,23.70,7579.02,8,UPI,2024-10-16,October,10,4,2024
1,2,Christopher Shannon,Chennai,East,Groceries,Oil,36664.41,10.21,6428.30,2,Card,2024-09-05,September,9,3,2024
2,3,Amanda Baker,Madurai,South,Furniture,Sofa,43582.84,26.96,6726.70,3,Net Banking,2024-04-14,April,4,2,2024

## City-wise Sales — Geographic Bubble Map

Visualize total sales across Tamil Nadu cities on an **interactive map**, with bubble size and color representing sales volume.

In [ ]:
city_sales=(df.groupby(['city','latitude','longitude'],as_index=False)['sales'].sum())


fig=px.scatter_map(city_sales,
                   lat='latitude',
                   lon='longitude',
                   size='sales',
                   color='sales',
                   hover_name='city',
                   title='city wise sales',
                   zoom=5)

fig.show()

In [ ]:
category_sales = (
    df.groupby(['category', 'product'], as_index=False)['sales']
      .sum()
)

fig = px.sunburst(
    category_sales,
    path=['category', 'product'],
    values='sales',
    title='Sales Distribution by Category& Product'
)

fig.show()

In [ ]:
df.to_csv('clean_retail_dataset.csv',index=False)

https://chat.deepseek.com/a/chat/s/4be07013-2ec2-4fac-a9b8-885eb88ba8d1